// generated by tb/test_top.py --gen - do not edit
`ifndef TB_PARAMS_VH
`define TB_PARAMS_VH
`define TB_MATRIX_SIZE 4
`define TB_DATA_WIDTH 8
`define TB_RESULT_W 18
`define TB_TILE_BEATS 9
`define TB_TILE_BYTES 36
`define TB_TILE_WORDS 4
`define TB_WEIGHTS_JOB 8
`define TB_LEVEL_W 4
`define TB_ST_TILE_LSB 20
`define TB_TILES 8
`define TB_STIM_WORDS 36
`define TB_GOLD_WORDS 72
`endif
