from __future__ import annotations
import json
import re
import sys
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
PKG = ROOT / "rtl" / "sys_pkg.sv"
VECTORS = ROOT / "tb" / "vectors"

SRC_BASE, DST_BASE, ALT_DST = 0x1000, 0x2000, 0x3000
TB_TILES = 16
_LP = re.compile(r"localparam\s+(?:integer|int|logic(?:\s+\[[^\]]+\])?)\s+(\w+)\s*=\s*([^;]+);")

def pkg_params():
    env = {"clog2": lambda x: max(1, (int(x) - 1).bit_length())}
    out = {}
    for name, expr in _LP.findall(PKG.read_text()):
        e = (expr.replace("$clog2", "clog2").replace("sys_pkg::", "")
             .replace("8'h", "0x").replace("32'h", "0x"))
        try:
            out[name] = int(eval(e, {"__builtins__": {}}, {**env, **out}))
        except Exception:
            continue
    return out


def pack_row(row, data_w):
    mask = (1 << data_w) - 1
    return sum((int(v) & mask) << (data_w * c) for c, v in enumerate(row))


def pack_tile(m, n, result_w, tile_beats):
    mask = (1 << result_w) - 1
    stream = 0
    for j, v in enumerate(np.asarray(m, np.int64).ravel()):
        stream |= (int(v) & mask) << (result_w * j)
    return [(stream >> (32 * i)) & 0xFFFFFFFF for i in range(tile_beats)]


def make_stream(p, rng, tiles):
    n, dw = p["MATRIX_SIZE"], p["DATA_WIDTH"]
    lim = 1 << (dw - 1)
    rand = lambda: rng.integers(-lim, lim, (n, n)).astype(np.int64)
    extreme = np.full((n, n), -lim, np.int64)
    b = rand()
    a = []
    for i in range(tiles):
        if i == 0:
            a.append(extreme)
        elif i == 1:
            a.append(np.full((n, n), lim - 1, np.int64))
        elif i == 2:
            a.append(np.zeros((n, n), np.int64))
        elif i == 3:
            m = np.zeros((n, n), np.int64)
            np.fill_diagonal(m, lim - 1)
            a.append(m)
        elif i % 2 == 0:
            a.append(rng.choice([-lim, -1, 0, 1, lim - 1], size=(n, n)).astype(np.int64))
        else:
            a.append(rand())
    words = [pack_row(r, dw) for r in b] + [pack_row(r, dw) for t in a for r in t]
    return b, a, words


def write_vectors(seed=7, tiles=TB_TILES):
    p = pkg_params()
    n, dw, rw = p["MATRIX_SIZE"], p["DATA_WIDTH"], p["RESULT_W"]
    tile_beats = (n * n * rw) // 32
    weights_job = 2 * n
    b, a, words = make_stream(p, np.random.default_rng(seed), tiles)
    gold = [w for t in a for w in pack_tile(np.asarray(t) @ b, n, rw, tile_beats)]

    VECTORS.mkdir(parents=True, exist_ok=True)
    (VECTORS / "stim.hex").write_text("".join(f"{w:08x}\n" for w in words))
    (VECTORS / "golden.hex").write_text("".join(f"{w:08x}\n" for w in gold))

    defs = {
        "MATRIX_SIZE": n,
        "DATA_WIDTH": dw,
        "RESULT_W": rw,
        "TILE_BEATS": tile_beats,
        "TILE_BYTES": tile_beats * 4,
        "TILE_WORDS": n,
        "WEIGHTS_JOB": weights_job,
        "LEVEL_W": p["LEVEL_W"],
        "ST_TILE_LSB": p["ST_TILE_LSB"],
        "TILES": tiles,
        "STIM_WORDS": len(words),
        "GOLD_WORDS": len(gold),
        "SRC_BASE": SRC_BASE,
        "DST_BASE": DST_BASE,
        "ALT_DST": ALT_DST,
        "AXI_ADDR_W": p["AXI_ADDR_W"],
        "AXI_DATA_W": p["AXI_DATA_W"],
        "MEM_WORDS": 4096,
        "CLK_HALF": 5000,
        "WATCHDOG": 500_000_000,
        "LEN_MASK": (1 << p["LEN_W"]) - 1,
        "NJOBS_MASK": (1 << p["NJOB_W"]) - 1,
        **{k: p[k] for k in p if k.startswith(("CTRL_", "ST_", "REG_"))},
    }
    lines = ["// auto-generated by tb/gen_vectors.py - do not edit", "`ifndef TB_PARAMS_VH", "`define TB_PARAMS_VH"]
    for k, v in defs.items():
        if k.startswith("REG_"):
            lines.append(f"`define TB_{k} 8'h{int(v):02X}")
        elif k.endswith("_BASE") or k == "ALT_DST":
            lines.append(f"`define TB_{k} 32'h{int(v):08X}")
        elif k.endswith("_MASK"):
            lines.append(f"`define TB_{k} 32'h{int(v):08X}")
        else:
            lines.append(f"`define TB_{k} {int(v)}")
    lines.append("`endif")
    (VECTORS / "tb_params.vh").write_text("\n".join(lines) + "\n")
    (VECTORS / "meta.json").write_text(json.dumps(defs, indent=2) + "\n")
    print(f"vectors: {tiles} tiles, {len(words)} stim words, {n}x{n}")


if __name__ == "__main__":
    write_vectors()
    sys.exit(0)
